### ISSUE TITLE
Screencast Walkthrough

### ISSUE THREAD

**Issue by t1600259** [DrMattG/SDGsR#3]
Hello Dr. Grainger,

I am relatively new to RStudio and Github. Still, I have taught my Japanese university students the importance of understanding and achieving the UN Sustainable Development Goals for several years. I want my students to use your SDGsR package to visualize the data in RStudio, but I am having trouble right out of the gates. 

I have already forked your Github repository for SDGsR, but would you happen to have a screencast video walkthrough for a newb like me who cannot seem even to load the package? I know you are very busy, but I would be forever grateful if you have time to post a video walkthrough like this (or if one is already available). It would be awesome to see how you are wrangling and visualizing the SDG data. 

Best regards,

Jon G.

**Comment by DrMattG** [comment]
Hi Jon,
I haven't done a screencast but I do have vignettes [here](https://drmattg.github.io/SDGsR/index.html) in the Articles menu. This [vignette](https://drmattg.github.io/SDGsR/articles/Introduction_to_SDGsR.html) has the most straight-forward example (although I see you will also need to load the tidyverse package). 

You can install the package using
 `devtools::install_github(“DrMattG/SDGsR”,dependencies = TRUE)`

Using your fork you could build the package locally (in RStudio there is a tab called "Build" and you would click "install and restart").  

I have always been a bit uncertain of what to do with this package - if you can think of some improvements feel free to let me know or to send a pull request. 

Let me know what goes wrong - as I am sure there will be bugs! 

Cheers
Matt

**Comment by t1600259** [comment]
Hi Dr. Grainger,

Thanks a lot for the quick response. I followed the instructions from the vignette, but I am running into the same error messages (screenshot below). I will give it a go with the build option that you mentioned, but I think I am in need of more RStudio practice to get this right. I do appreciate your assistance and I hope that I can get my students to use your SDGsR package because I believe it will be a valuable learning experience for them (and me!). Thanks again and have a great day.

Best regards,
Jon
![SDGsR_Package](https://user-images.githubusercontent.com/102738754/173712667-b8a58f1b-f87d-4fdd-abc1-0f9925efed4b.png)

**Comment by DrMattG** [comment]
Hi Jon,
It looks like the “ symbol is not being read correctly in R. Try and delete
them and put them back in or use single quotation marks ‘ ‘

Matt

**Comment by t1600259** [comment]
Hi Dr. Grainger,

Thanks again for your help with this. I tried opening it in RStudio Cloud and I got a notification that [kableExtra] needs to be installed first. I went ahead and installed that package and then your SDGsR package would load properly both with the double " marks as well as the single ' mark. (screenshot below). Enjoy the rest of your week. 

Best regards,

Jon


![kableExtra](https://user-images.githubusercontent.com/102738754/173772924-d3446888-bc3e-415f-b9fd-480238e31df5.png)

**Comment by DrMattG** [comment]
Great! Please let me know if you have any suggestions (or more problems). I am in the field for the next two days so will be less responsive! I will close this issue now but feel free to open new issues.

I forgot to say have a look at the vignettes for viz ideas - there are no doubt better ways to do it (suggestions are welcome). I enjoyed playing with the circular plots. Vignettes are [here](https://drmattg.github.io/SDGsR/index.html) in the Articles menu.

Matt
